# Generated by Django 5.1.2 on 2024-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_score', models.FloatField(default=100.0)),
                ('core', models.BooleanField(default=False)),
            ],
        ),
    ]
