# Generated by Django 5.1.1 on 2024-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_alter_faculty_university_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteriaset",
            name="name",
            field=models.CharField(default="Unnamed CriteriaSet", max_length=50),
        ),
    ]
