# Generated by Django 5.1.2 on 2024-11-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_scorehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaset',
            name='name',
            field=models.CharField(default='Unnamed CriteriaSet', max_length=200),
        ),
    ]
