from .uni_serializer import UniversitySerializer, FacultySerializer, MajorSerializer
from .exam_serializer import ExamSerializer
from .criteria_serializer import CriteriaSetSerializer, CriterionSerializer
from .exam_score_serializer import ExamScoreSerializer