name: Run tests and upload coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Create .env file
        run: |
          touch .env
          echo "SECRET_KEY = ${{secrets.SECRET_KEY}}" >> .env
          echo ALLOWED_HOSTS="${{ secrets.ALLOWED_HOSTS }}" >> .env
          echo DEBUG="${{ secrets.DEBUG }}" >> .env
          echo TIME_ZONE="${{ secrets.TIME_ZONE }}" >> .env
          echo CLIENT_ID="${{ secrets.CLIENT_ID }}" >> .env
          echo SECRET="${{ secrets.SECRET }}" >> .env
          cat .env

      - name: Run Migrations
        run: |
            python manage.py makemigrations
            python manage.py migrate

      - name: Run tests
        run: coverage run --branch manage.py test manager

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
