# Generated by Django 4.2.15 on 2024-10-05 13:52

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taskboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(default='TODO', max_length=20)),
                ('end_date', models.DateTimeField(default=manager.models.today_midnight, verbose_name='End date')),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('taskboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.taskboard')),
            ],
        ),
    ]
