# Generated by Django 5.1.2 on 2024-11-13 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='parent',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='parent',
            field=models.ManyToManyField(related_name='student_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
