# Generated by Django 5.1.2 on 2024-11-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_event_end_date_and_more'),
        ('manager', '0009_remove_studentinfo_parent_studentinfo_parent'),
    ]

    operations = [
    ]
